tap 'caskroom/cask'

brew 'ansible'
brew 'caskroom/cask/brew-cask'
brew 'git'
brew 'jvgrep'
brew 'node'
brew 'tig'
brew 'tmux'
brew 'vim',args:['with-lua']
brew 'wget'
brew 'zsh'

cask 'appcleaner'
cask 'karabiner'
cask 'cyberduck'
cask 'dropbox'
cask 'evernote'
cask 'firefox'
cask 'google-chrome'
cask 'google-drive'
cask 'google-japanese-ime'
cask 'iterm2'
cask 'mysqlworkbench'
cask 'p4merge'
cask 'sequel-pro'
cask 'slack'
# cask 'sophos-anti-virus-home-edition'
cask 'the-unarchiver'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
